### ISSUE TITLE
Unresponsive maintainers report.

### ISSUE THREAD

**Issue by williamspatrick** [openbmc/technical-oversight-forum#27]
**Background** 

Per https://github.com/openbmc/docs/blob/master/process/subproject-maintainership.md:

> Maintainers are considered unresponsive after failing to address contributions for a minimum period of 1 month.

The following trivial commits were submitted on April 12th and have not received feedback, nor has a follow up ping on May 2nd been acknowledged:

* openbmc/telemetry - https://gerrit.openbmc.org/c/openbmc/telemetry/+/62378
* openbmc/service-config-manager - https://gerrit.openbmc.org/c/openbmc/service-config-manager/+/62387
* openbmc/phosphor-misc - https://gerrit.openbmc.org/c/openbmc/phosphor-misc/+/62392

**Questions**

- Do these examples satisfy the "unresponsive" requirements outlined in the process?
- How does the TOF record unresponsiveness and/or follow up with affected maintainers?

**Comment by bradbishop** [comment]
FWIW I merged openbmc/phosphor-misc - https://gerrit.openbmc.org/c/openbmc/phosphor-misc/+/62392 just now.  I don't check my repositories very often.  I need to set up some better mail filtering...

**Comment by amboar** [comment]
## Merged

62378: meson: remove deprecated get_pkgconfig_variable | https://gerrit.openbmc.org/c/openbmc/telemetry/+/62378
62392: meson: remove deprecated get_pkgconfig_variable | https://gerrit.openbmc.org/c/openbmc/phosphor-misc/+/62392

## Unreviewed

62387: meson: remove deprecated get_pkgconfig_variable | https://gerrit.openbmc.org/c/openbmc/service-config-manager/+/62387

> How does the TOF record unresponsiveness and/or follow up with affected maintainers?

I didn't really spell that out, but I figured we just email a warning to the set of maintainers and CC openbmc@lists.ozlabs.org to make sure the communication is public.

**Comment by williamspatrick** [comment]
Additional commits which have had over a month elapse:

* openbmc/service-config-manager - https://gerrit.openbmc.org/c/openbmc/service-config-manager/+/63275
* openbmc/ipmi-fru-parser - https://gerrit.openbmc.org/c/openbmc/ipmi-fru-parser/+/63228
* openbmc/dbus-sensors - https://gerrit.openbmc.org/c/openbmc/dbus-sensors/+/63243
* openbmc/phosphor-ecc - https://gerrit.openbmc.org/c/openbmc/phosphor-ecc/+/63285
* openbmc/bios-settings-manager - https://gerrit.openbmc.org/c/openbmc/bios-settings-mgr/+/63276
* openbmc/pfr-manager - https://gerrit.openbmc.org/c/openbmc/pfr-manager/+/63270

**Comment by amboar** [comment]
The patches for each of openbmc/dbus-sensors, openbmc/telemetry, and openbmc/phosphor-misc patches have all been merged at this point in time. I've held off on sending notifications of unresponsiveness for those projects.

For the remaining projects listed, the notifications are now on the list:

* openbmc/service-config-manager: https://lore.kernel.org/openbmc/afb45974-9153-42d6-a53f-a8f74ef68d61@app.fastmail.com/
* openbmc/ipmi-fru-parser: https://lore.kernel.org/openbmc/f086d7a4-7363-4e90-b070-af7ab65a6475@app.fastmail.com/
* openbmc/phosphor-ecc: https://lore.kernel.org/openbmc/44c7eb21-fff5-4300-9a81-b89848245dc0@app.fastmail.com/
* openbmc/bios-settings-manager: https://lore.kernel.org/openbmc/f21a5062-b462-4597-8770-4869b0071ba2@app.fastmail.com/
* openbmc/pfr-manager: https://lore.kernel.org/openbmc/dd227a06-3bc5-4fda-abb2-520fad34c026@app.fastmail.com/

**Comment by williamspatrick** [comment]
https://gerrit.openbmc.org/c/openbmc/ipmi-fru-parser/+/63228 is still not resolved.  @amboar

**Comment by williamspatrick** [comment]
> https://gerrit.openbmc.org/c/openbmc/ipmi-fru-parser/+/63228 is still not resolved. @amboar

The lack of maintainer attention on `ipmi-fru-parser` is also affecting getting more useful changes into the repository (beyond simply reformatting so that CI passes):

- https://gerrit.openbmc.org/c/openbmc/ipmi-fru-parser/+/58446

**Comment by amboar** [comment]
@williamspatrick I've addressed both of the ipmi-fru-parser patches mentioned above in the second notification as follows:

https://lore.kernel.org/openbmc/d47818d4-4167-4508-bec0-db6eee93edb0@app.fastmail.com/

**Comment by williamspatrick** [comment]
Closing now.  All reports are resolved.
